name: Parallel Test Flow Build
on: push
jobs:
  Add-To-Cart:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
         command: npm run test:addToCart

      - name: Cypress Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML Report - Add to Cart
          path: cypress/reports/html    


  Register-Flow-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
         command: npm run test:registerFlow 

      - name: Cypress Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML Report - Registration flow
          path: cypress/reports/html    